workshopapps/customersupport.web

backend/app/routers/sentiment.py
Added sentimental analysis script using NLTK(Natural language tool kit). The script accepts a transcript and returns a sentimental analysis that has a positivity score, negativity score, neutrality score and overall sentiment.
Linear issue link: https://linear.app/team-brainbox/issue/BAC-13/sentiment-analysis-service.
=> Feat(BAC-13): added sentimental analysis script

backend/app/schema.py
this code creates models representing the db schema
linear issue link: https://linear.app/team-brainbox/issue/BAC-4/design-the-models-representing-our-db-schema
=> feat(BAC-4): added models representing db schema

scrybe_frontend/src/App.jsx, scrybe_frontend/src/components/Industry/industryArticle.jsx, scrybe_frontend/src/styles/HowItWorks/HowItWorks.module.css, scrybe_frontend/src/styles/Industry/industry.module.css
Added responsiveness for breakpoints on smaller screens.
This is ready to be merged to the main repo for Scrybe
=> merging from changes from local repo, damola-dev branch

scrybe_frontend/src/App.jsx
corrected path/ to How It Works page
=> feat: corrected path/ to How It Works page

backend/app/emails.py, backend/app/main.py, backend/app/requirements.txt
Reverts workshopapps/customersupport.web#207
=> Revert "Revert "Feat/bac 7 user email verification""

scrybe_frontend/src/pages/LeaderBoard/Leaderboard.module.scss
Fixes done & Adjustment
. Top bar section - adjusted padding
. Removed the extra spacing on the search bar 
. resized calendar icon & for a smaller screen
. Worked on pagination
. reduced the spacing between calendar icon & dropdown
=> fix: updated-styling/Leaderboard

scrybe_frontend/src/pages/Industry/components/IndustryCard/IndustryCard.module.scss
ran "git config core.ignorecase false"
=> style: just git config ignorecase false

scrybe_frontend/src/pages/DashboardOverview/DashboardOverview.module.scss, scrybe_frontend/src/pages/DashboardOverview/index.jsx
Reverts workshopapps/customersupport.web#333
=> Revert "fix(FRO-31):add Sidebar"

scrybe_frontend/src/App.jsx, scrybe_frontend/src/interceptors/axios.jsx, scrybe_frontend/src/main.jsx, scrybe_frontend/src/pages/Account/index.jsx, scrybe_frontend/src/pages/SignIn/SignIn.jsx, scrybe_frontend/src/pages/SignUp/SignUp.jsx
=> Feat/fro 17 Sign Up and Log In Logic Done

scrybe_frontend/src/App.jsx, scrybe_frontend/src/components/footer/footer.module.scss
Fixed the top thickness of the border top component.
(Link to task on Linear)[https://linear.app/team-brainbox/issue/FRO-129/heed-footer-2]
=> Fix: Footer Component Border Top Thickness / Opacity

scrybe_frontend/src/pages/UploadRecordings/index.jsx
PR to fix ticket FRO-123
Expected result:
```
General Sidebar
```
Actual Result:
```
Showing the main page Sidebar that makes the page flow and user Interaction work
```
New Result:
```
Changed to the General sidebar, but more work is to be done on the main General sidebar
```
=> Tickect-FRO-123

scrybe_frontend/src/components/navBar/index.jsx, scrybe_frontend/src/components/navBar/nav.module.scss, scrybe_frontend/src/components/navBar_free/index.jsx, scrybe_frontend/src/components/navBar_free/nav.module.scss
```
Correct all Links in the navbar menu
```
If the Industry page is restored then I will restore back the Industry menu link
=> ticket-FRO-89

scrybe_frontend/src/pages/DashboardOverview/DashboardOverview.module.scss, scrybe_frontend/src/pages/DashboardOverview/Data.js, scrybe_frontend/src/pages/DashboardOverview/hooks/index.jsx, scrybe_frontend/src/pages/DashboardOverview/index.jsx
**Link to linear ticket: https://linear.app/team-brainbox/issue/FRO-103/heed-dashboard-3**
=> Feat/fro 103/heed dashboard 3

backend/app/crud.py, backend/app/main.py, backend/app/models.py
Created an endpoint that allows logged-in users to add agents to the platform. The agent so added is automatically linked to the user's company and can be returned on the user's accounts dashboard.
=> Created an endpoint to add agents

scrybe_frontend/src/pages/LeaderBoard/Leaderboard.jsx, scrybe_frontend/src/pages/LeaderBoard/Leaderboard.module.scss
**Linear Ticket link:**
- https://linear.app/team-brainbox/issue/FRO-111/heed-leaderboard-4
**Linear Ticket Description**
- Fix Responsiveness Issue
**What work was implemented?**
- Adjusted the styling for small screen responsiveness.
- Fix the input sizing to sit well for different screen size.
- Added the Sidebar positioning to fit well on page.
=> Fix: FRO-111/heed-leaderboard-4

scrybe_frontend/src/pages/HelpAndSupport/components/Cards/Cards.jsx
The "Start Transcribe Button" is not working, fix it
After discussions with the Designers and PM  I had the go ahead to remove the button
https://www.figma.com/file/5YfxPD9L4AeaFwmEtM6Ebt/Brainbox-Project?node-id=3764%3A41023&t=Lsei5GwpjhgA9dfq-4
=> Fro/142/help page: https://linear.app/team-brainbox/issue/FRO-142/heed-help-and-support

scrybe_frontend/src/pages/Logout/index.jsx, scrybe_frontend/src/pages/SignIn/SignIn.jsx, scrybe_frontend/src/pages/SignUp/SignUp.jsx
Linear ticket link: https://linear.app/team-brainbox/issue/FRO-118/heed-authentication-3
=> Store cookies for each session and destroy them on logout

scrybe_frontend/src/pages/Error/Error.module.scss
=> fix: fix error color

scrybe_frontend/src/pages/DashboardOverview/DashboardOverview.module.scss, scrybe_frontend/src/pages/DashboardOverview/Data.js, scrybe_frontend/src/pages/DashboardOverview/components/RecentRecording.jsx, scrybe_frontend/src/pages/DashboardOverview/components/TotalAnalysis.jsx, scrybe_frontend/src/pages/DashboardOverview/components/TotalRecording.jsx
**Implement the new Dashboard Design.**
**Make Dashboard Overview Responsive** 
**Update the Sidebar for new Dashboard.** 
**Work on the new LeaderBoard Design**
**Implement the new Total Analysis Chart.**
**Linear Link:** https://linear.app/team-brainbox/issue/FRO-157/heed-dashbord-overview
=> Implement the new Dashboard Design.

scrybe_frontend/src/pages/AgentReport/index.jsx, scrybe_frontend/src/pages/NewLandingPageSalesTeam/Hero/index.jsx
Changed agent report page sidebar to the new one
=> Feat:changed agent report page sidebar to the new one.

scrybe_frontend/src/App.jsx, scrybe_frontend/src/helpers/axioshelp/index.jsx, scrybe_frontend/src/interceptors/axios.jsx, scrybe_frontend/src/pages/EmailVerifySuccess/index.jsx, scrybe_frontend/src/pages/SignIn/SignIn.jsx, scrybe_frontend/src/pages/SignUp/SignUp.jsx, scrybe_frontend/src/pages/UploadRecordings/TableData/index.jsx
fixed not able to create account and sign in issues
=> Auth fixes

scrybe_frontend/src/pages/ForgetPassword/ForgetPassword.jsx, scrybe_frontend/src/pages/SetNewPassword/SetNewPassword.jsx
Linear Ticket link: https://linear.app/team-brainbox/issue/FRO-120/heed-authentication-5
**My PR Fixes ID-linear_ticket_number_FRO-120**
Refixed the errors that occurred in the forgot and reset password files
Refix the errors that occurred in the forgot and reset password files
- I refixed the errors that occurred in the forgot and reset password files
=> Refixed the errors that occurred in the forgot and reset password files

scrybe_frontend/src/App.jsx, scrybe_frontend/src/pages/Checkout/Startup/checkout.module.scss, scrybe_frontend/src/pages/Checkout/Startup/index.jsx, scrybe_frontend/src/pages/Checkout/index.jsx, scrybe_frontend/src/pages/Pricing/Pricing.module.scss, scrybe_frontend/src/pages/Pricing/components/MonthPlan/monthplans.module.scss, scrybe_frontend/src/pages/Pricing/components/YearPlan/yearplans.module.scss
Added hover state on all buttons on Pricing page
=> Fro 139 - Pricing page

scrybe_frontend/src/components/NewDesignSidebar/generalSidebar.module.scss, scrybe_frontend/src/components/NewDesignSidebar/index.jsx, scrybe_frontend/src/helpers/fetchCurrentUser/index.jsx
Reverts workshopapps/customersupport.web#515
=> Revert "dynamic sidebar"

scrybe_frontend/src/components/NewDesignSidebar/generalSidebar.module.scss, scrybe_frontend/src/components/NewDesignSidebar/index.jsx, scrybe_frontend/src/helpers/fetchCurrentUser/index.jsx
fetch user account details and display on sidebar
=> dynamic sidebar

scrybe_frontend/src/helpers/axioshelp/apis/index.js, scrybe_frontend/src/helpers/axioshelp/axios.js, scrybe_frontend/src/helpers/axioshelp/index.jsx, scrybe_frontend/src/pages/DashboardOverview/components/RecentRecording.jsx, scrybe_frontend/src/pages/DashboardOverview/components/TotalAnalysis.jsx, scrybe_frontend/src/pages/DashboardOverview/components/TotalRecording.jsx, scrybe_frontend/src/pages/DashboardOverview/hooks/index.js, scrybe_frontend/src/pages/DashboardOverview/index.jsx, scrybe_frontend/src/pages/SignIn/SignIn.jsx
Refactored the hooks to limit the calls made to the backend
=> chore : refactored the dashboard api calls

scrybe_frontend/src/pages/LeaderBoard/Leaderboard.module.scss, scrybe_frontend/src/pages/LeaderBoard/Leaderboard2.jsx
**Linear Ticket**
https://linear.app/team-brainbox/issue/FRO-110/heed-leaderboard-3
**Linear Ticket Description**
- List all agents dynamically
**What work was implemented?**
- I worked with the backend guy to initialize the endpoint required for the Leaderboard page according to the UI/UX design.
- Updated the Topbar Menu to be functional according to the agent logged in.
- Updated the Sidebar menu to the new design
- I map the leaderboard endpoint to initialize all the agents dynamically.
- Make corrections to styling on few section.
=> Fix: Heed-FRO-110/Leaderboard-Endpoint

scrybe_frontend/src/components/NavbarFree/index.jsx, scrybe_frontend/src/components/NavbarFree/nav.module.scss, scrybe_frontend/src/components/TopNav/index.jsx, scrybe_frontend/src/helpers/formatAudioLen/index.js, scrybe_frontend/src/helpers/formatAudioSize/index.js, scrybe_frontend/src/helpers/formatDate/index.js, scrybe_frontend/src/helpers/shortenFileLen/index.js, scrybe_frontend/src/pages/UploadRecordings/TableData/index.jsx, scrybe_frontend/src/pages/UploadRecordings/TableData/tabledata.module.scss
=> Ticket fro 122

scrybe_frontend/src/pages/Settings/MainPage/Settings.jsx, scrybe_frontend/src/pages/Settings/SettingsPageSubPages/AccountSettings/AccountSettings.jsx, scrybe_frontend/src/pages/Settings/SettingsPageSubPages/AccountSettings/AccountSettings.module.scss
- Dynamically rendered user's info on the Settings Page
- Validated the change password form
- Sent new password to server
=> feat(FRO-121): Implement Change password API call on Settings page

scrybe_frontend/src/pages/AboutUs/About.module.scss, scrybe_frontend/src/pages/AboutUs/index.jsx, scrybe_frontend/src/pages/HomePageRedesign/homePageRedesign.module.scss, scrybe_frontend/src/pages/HomePageRedesign/index.jsx
Corrections: I fixed misalignment of the page with the header and add hover effects on the buttons.
=> Fix misalignment of the page with the header and add hover effects on the buttons

scrybe_frontend/src/components/LoadingSkeleton/index.jsx, scrybe_frontend/src/components/LoadingSkeleton/loading.module.scss, scrybe_frontend/src/helpers/formatAudioLen/index.js, scrybe_frontend/src/pages/UploadRecordings/TableData/index.jsx, scrybe_frontend/src/pages/UploadRecordings/TableData/tabledata.module.scss
added loading skeleton and fixed session expired style
=> fixed session expired style, added is loading ui

backend/app/crud.py, backend/app/main.py
made adjustments to the agent performance and leaderboard
=> adjusted endpoint

backend/app/main.py, backend/app/requirements.txt
I have configured the Kibana APM in the main.py file.
=> Kibana APM configured

backend/app/crud.py, backend/app/models.py, backend/app/schema.py
And also reformated the accounts endpoint to fit what the front-end dev requires.
=> Added a field for location in the agent table

scrybe_frontend/src/pages/Account/account.module.scss, scrybe_frontend/src/pages/Account/index.jsx
Reverts workshopapps/customersupport.web#634
=> Revert "Dev"

scrybe_frontend/src/pages/LeaderBoard/Leaderboard.jsx, scrybe_frontend/src/pages/VerificationEmail/EmailVerify.jsx
**Linear Ticket**
https://linear.app/team-brainbox/issue/FRO-111/heed-leaderboard-4
**What was done**
I consumed the new endpoint provided for the leaderboard page to show weekly & monthly data on dropdown click
=> Add: Monthly & Weekly-Endpoint//FRO-111/heed-leaderboard-4

scrybe_frontend/src/pages/CheckMail/checkMail.module.scss, scrybe_frontend/src/pages/CheckMail/index.jsx, scrybe_frontend/src/pages/HomePageRedesign/homePageRedesign.module.scss, scrybe_frontend/src/pages/HomePageRedesign/index.jsx
Linear Ticket link: https://linear.app/team-brainbox/issue/FRO-168/zuri-chat-implementation-of-the-forgot-to-reset-password-pages-new
**My PR Fixes ID-linear_ticket_number_FRO-168**
Worked on the new designs for Forget password to Reset Password pages.
Implementation of the Forgot to Reset password pages new designs
- I implemented the new designs for Forgot password to Reset password changes
- I implemented the Mobile view responsiveness as designed.
=> Implementation of the Forgot to Reset password pages new designs

backend/app/crud.py, backend/app/main.py
corrected the source of the internal server error on agent leaderboard
=> Adjusted endpoints

scrybe_frontend/src/components/Footer/index.jsx, scrybe_frontend/src/pages/LeaderBoard/Leaderboard.jsx, scrybe_frontend/src/pages/LeaderBoard/Leaderboard.module.scss, scrybe_frontend/src/pages/Support/Help/Help.module.scss, scrybe_frontend/src/pages/Support/HowItWorks/HowItWorks.module.scss, scrybe_frontend/src/pages/Support/Subscribe/subscribe.module.scss
**Linear Ticket Link:**
https://linear.app/team-brainbox/issue/FRO-111/heed-leaderboard-4
https://linear.app/team-brainbox/issue/FRO-85/heed-landing-page-support
**What was done**
- Updated the card color changes & total average score color required in design by adding indexing.
- CSS spacing between cards & content
- Drop down consumes monthly & weekly endpoints.
- Added a logic statement to place a "message text" when Agent data is in an empty state.
- Support team now aligns properly, content are aligned between the width of footer.
=> Add: Leaderboard changes & support team 

scrybe_frontend/src/pages/NewSignupVerify/index.jsx, scrybe_frontend/src/pages/PartnersPage/index.jsx, scrybe_frontend/src/pages/PressArticle/index.jsx, scrybe_frontend/src/pages/PressPage/index.jsx
Import heed navbar to Partners, Press, and Press Article pages
=> feat: import heed navbar to Partners, Press, and Press Article pages

backend/app/main.py
The most recent audios now come first.
=> minor ordering fix

scrybe_frontend/src/App.jsx, scrybe_frontend/src/HOCs/hooks/useAuth.js, scrybe_frontend/src/components/NavbarFreeTry/index.jsx, scrybe_frontend/src/pages/AboutUs/index.jsx, scrybe_frontend/src/pages/Account/index.jsx, scrybe_frontend/src/pages/ForgetPassword/ForgetPassword.jsx, scrybe_frontend/src/pages/HomePageA/HeroSection/index.jsx, scrybe_frontend/src/pages/NewLandingPageSalesTeam/Hero/index.jsx, scrybe_frontend/src/pages/NewPasswordResetSuccessful/index.jsx, scrybe_frontend/src/pages/PasswordResetSuccessful/PasswordResetSuccessful.jsx, scrybe_frontend/src/pages/Pricing/index.jsx, scrybe_frontend/src/pages/Settings/SettingsPageSubPages/PersonalInformation/PersonalInformationSettings.jsx, scrybe_frontend/src/pages/SignIn/SignIn.jsx, scrybe_frontend/src/pages/SignUp/SignUp.jsx, scrybe_frontend/src/pages/Support/Hero/index.jsx, scrybe_frontend/src/pages/TryForFree - Copy/components/Try_hero/index.jsx, scrybe_frontend/src/pages/TryForFree - Copy/components/Try_state_3/index.jsx, scrybe_frontend/src/pages/TryForFree - Copy/components/Try_state_4/index.jsx, scrybe_frontend/src/pages/TryForFree/components/Try_hero/index.jsx, scrybe_frontend/src/pages/TryForFree/components/Try_state_3/index.jsx, scrybe_frontend/src/pages/TryForFree/components/Try_state_4/index.jsx, scrybe_frontend/src/pages/VerificationEmail/EmailVerify.jsx
* fix: corrected text
* fix: added protected routes
* Update index.jsx
* fix: styling and file-size corrections
* fix: display text
* fix: remove all /create-account and /signin links
=> fix: remove all /create-account and /signup routes (#769)

scrybe_frontend/src/pages/TranscribePage/Transcribe/Components/TranscriptionMain/TranscriptionsList/TranscriptionsList.module.scss, scrybe_frontend/src/pages/TranscribePage/Transcribe/Components/TranscriptionMain/TranscriptionsList/test.jsx
* fix: corrected text
* fix: added protected routes
* Update index.jsx
* fix: styling and file-size corrections
* fix: display text
* fix: remove all /create-account and /signin links
* style: fixed upload button
* fix: hide google login
* feat: added refresh page button to transcription page
=> feat: added refresh page button to transcription page (#790)

scrybe_frontend/src/pages/LeaderBoard/Leaderboard.jsx
Leaderboard Modified
Text grammar corrected
Filter search modified
=> Add: Resolved conflict with duplication of card

scrybe_frontend/src/pages/LeaderBoard/Leaderboard.jsx
Reverts workshopapps/customersupport.web#793
=> Revert "Add: Resolved conflict with duplication of card"

backend/app/main.py, backend/app/routers/users.py
I created new google credentials and refactored the google login codes: moved the google oauth configuration from main to the user router and imported the necessary dependencies.
It works well now, returning the tokens needed by the frontend dev.
=> Fixed Google signin

scrybe_frontend/package-lock.json, scrybe_frontend/src/components/Footer/footer.module.scss, scrybe_frontend/src/components/Footer/index.jsx
i removed some unnecessary things and added the new social handles
=> made changes to the footer

backend/app/models.py
Made the agent_id to be 6 digits long, and unique as requested
=> Fix: Agent_id

backend/app/emails.py, backend/app/models.py, backend/app/requirements.txt, backend/app/routers/orders.py, backend/templates/TopUp/failure.html, backend/templates/TopUp/success.html
integrated stripe payment system to pay for top up on heed
=> Stripe payment system integration.

scrybe_frontend/src/App.jsx, scrybe_frontend/src/main.jsx, scrybe_frontend/src/pages/FinalLoginPage/Login.jsx, scrybe_frontend/src/pages/UploadedRecordings/TableData/index.jsx, scrybe_frontend/src/redux/axios/apis/agent.js, scrybe_frontend/src/redux/axios/apis/analyze.js, scrybe_frontend/src/redux/axios/apis/audio.js, scrybe_frontend/src/redux/axios/apis/orders.js, scrybe_frontend/src/redux/axios/apis/sentiment.js, scrybe_frontend/src/redux/axios/apis/transciptions.js, scrybe_frontend/src/redux/axios/apis/user.js, scrybe_frontend/src/redux/axios/axios.js, scrybe_frontend/src/redux/features/audios/audioSlice.js, scrybe_frontend/src/redux/features/audios/service.js
this PR completes redux setup in uploaded recordings page
=> completed redux setup on uploaded pages

backend/templates/Deactivation/index.html, backend/templates/Deletion/index.html, backend/templates/EmailVerification/index.html, backend/templates/ResetPassword/index.html
I made the corrections by making view responsive and adding the red color
=> Adjustments to email templates

scrybe_frontend/src/pages/DashboardOverview/DashboardOverview.module.scss, scrybe_frontend/src/pages/DashboardOverview/components/LeaderBoard.jsx, scrybe_frontend/src/pages/DashboardOverview/components/RecentRecording.jsx, scrybe_frontend/src/pages/DashboardOverview/components/TotalAnalysis.jsx, scrybe_frontend/src/pages/DashboardOverview/components/TotalRecording.jsx, scrybe_frontend/src/pages/DashboardOverview/hooks/index.jsx, scrybe_frontend/src/pages/DashboardOverview/index.jsx, scrybe_frontend/src/pages/LeaderBoard/Leaderboard.jsx, scrybe_frontend/src/pages/LeaderBoard/Leaderboard.module.scss, scrybe_frontend/src/redux/axios/apis/sentiment.js, scrybe_frontend/src/redux/features/audios/service.js, scrybe_frontend/src/redux/features/sentiment/service.js, scrybe_frontend/src/redux/store.js
- Refactor page to fetch data from redux store
- Added Loading skeleton
- Fix page search
=> Refactor Dashboard
